### PR TITLE
:bug: Fix agent can't connect to the kafka cluster

### PR DESCRIPTION
**Pull request by yanmxa**
## Summary

1. The managed cluster cert generated by the addon registration will be overridden by the addon manifest work
2.  The deadlock when creating the kafkacluster before render the kafka resources
3. The transport config controller predicate issue

## Related issue(s)

Fixes # https://issues.redhat.com/browse/ACM-13717

### CODE REVIEW

**Comment by clyang82** [comment]
https://github.com/stolostron/multicluster-global-hub/blob/46eca72e3804148fbd56aa48057437fbca48ee10/operator/pkg/controllers/hubofhubs/transporter/protocol/byo_transporter.go#L79-L81
should we remove them for BYO case?

**Comment by yanmxa** [comment]
> ClientSecretName

Done!

**Comment by yanmxa** [comment]
e2e error 

```bash
\"manifestworkvalidators.admission.work.open-cluster-management.io\" denied the request: name must be set in manifest" logger="UnhandledError"
E0903 13:39:09.013820       1 base_controller.go:159] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"hub2/multicluster-global-hub-controller\", err: admission webhook \"manifestworkvalidators.admission.work.open-cluster-management.io\" denied the request: name must be set in manifest" logger="UnhandledError"
I0903 13:39:09.014230       1 prune_reconciler.go:79] Kafka and Postgres are provided by customer, disable metrics
E0903 13:39:09.160551       1 base_controller.go:159] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"hub1/multicluster-global-hub-controller\", err: admission webhook \"manifestworkvalidators.admission.work.open-cluster-management.io\" denied the request: name must be set in manifest" logger="UnhandledError"
E0903 13:39:09.235384       1 base_controller.go:159] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"hub2/multicluster-global-hub-controller\", err: admission webhook \"manifestworkvalidators.admission.work.open-cluster-management.io\" denied the request: name must be set in manifest" logger="UnhandledError"
E0903 13:39:09.640510       1 base_controller.go:159] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"hub1/multicluster-global-hub-controller\", err: admission webhook 
```

**Pull request merged**
