### PR TITLE
fix metric lost

### PR DESCRIPTION
**Pull request by ldpliu**
## Related issue(s)
https://issues.redhat.com/browse/ACM-15524
Fixes #
image

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [x] List other manual tests you have done.
       manually test it, and the metrics created.

### CODE REVIEW

**Comment by yanmxa** [comment]
Can you please give me more information about this fix, it seems you moved the registration work from initialization to add to manager?

**Comment by ldpliu** [comment]
> Can you please give me more information about this fix, it seems you moved the registration work from initialization to add to manager?

The main reason is that we missed to call : `task.RegisterMetrics()`

**Pull request merged**
