### PR TITLE
:sparkles:  Upgrade the postgres from 13 to 16

### PR DESCRIPTION
**Pull request by yanmxa**
## Related issue(s)

Fixes # https://issues.redhat.com/browse/ACM-16095

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [x] List other manual tests you have done.
```bash
❯ oc get pods
NAME                                                READY   STATUS    RESTARTS   AGE
kafka-entity-operator-7c8fd8d98f-wb7wd              2/2     Running   0          21m
kafka-kafka-0                                       1/1     Running   0          21m
multicluster-global-hub-grafana-849bcd8756-mw9sd    2/2     Running   0          15m
multicluster-global-hub-manager-698594c9-7wf7s      1/1     Running   0          15m
multicluster-global-hub-operator-7fd45749b7-dzbck   1/1     Running   0          18m
multicluster-global-hub-postgres-0                  2/2     Running   0          22m
multicluster-global-hub-postgresql-0                2/2     Running   0          15m
strimzi-cluster-operator-v0.43.0-76f57fb5b7-d79fj   1/1     Running   0          22m
❯ oc get secret storage-config
NAME             TYPE     DATA   AGE
storage-config   Opaque   2      16m
❯ kubectl exec -it multicluster-global-hub-postgres-0 -n multicluster-global-hub -- psql -U postgres -d hoh -c "SELECT * FROM status.leaf_hub_heartbeats;"

Defaulted container "multicluster-global-hub-postgres" out of: multicluster-global-hub-postgres, prometheus-postgres-exporter
 leaf_hub_name |       last_timestamp       | status
---------------+----------------------------+--------
 hub           | 2024-12-09 06:29:24.234394 | active
(1 row)
```
The status of the global hub operand
```bash
❯ oc get mgh multiclusterglobalhub -n multicluster-global-hub
NAME                    STATUS    AGE
multiclusterglobalhub   Running   103m
❯ oc get mgh multiclusterglobalhub -n multicluster-global-hub -oyaml
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.open-cluster-management.io/v1alpha4","kind":"MulticlusterGlobalHub","metadata":{"annotations":{},"name":"multiclusterglobalhub","namespace":"multicluster-global-hub"},"spec":{"availabilityConfig":"Basic","dataLayer":{"postgres":{"retention":"18m"}}}}
  creationTimestamp: "2024-12-09T06:22:18Z"
  finalizers:
  - global-hub.open-cluster-management.io/resource-cleanup
  generation: 1
  name: multiclusterglobalhub
  namespace: multicluster-global-hub
  resourceVersion: "13956322"
  uid: 0d9f63a5-9264-4865-86a9-050b40116077
spec:
  availabilityConfig: Basic
  dataLayer:
    kafka:
      topics:
        specTopic: gh-spec
        statusTopic: gh-status.*
    postgres:
      retention: 18m
  enableMetrics: true
status:
  components:
    kafka:
      kind: TransportConnection
      lastTransitionTime: "2024-12-09T08:03:47Z"
      message: Transport connection has set
      name: kafka
      reason: TransportConnectionSet
      status: "True"
      type: Available
    multicluster-global-hub-grafana:
      kind: Deployment
      lastTransitionTime: "2024-12-09T06:29:30Z"
      message: Component multicluster-global-hub-grafana has been deployed
      name: multicluster-global-hub-grafana
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    multicluster-global-hub-manager:
      kind: Deployment
      lastTransitionTime: "2024-12-09T08:03:49Z"
      message: Component multicluster-global-hub-manager has been deployed
      name: multicluster-global-hub-manager
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    multicluster-global-hub-postgres:
      kind: StatefulSet
      lastTransitionTime: "2024-12-09T06:22:32Z"
      message: Component multicluster-global-hub-postgres has been deployed
      name: multicluster-global-hub-postgres
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    multicluster-global-hub-postgresql:
      kind: StatefulSet
      lastTransitionTime: "2024-12-09T08:03:47Z"
      message: Component multicluster-global-hub-postgresql has been deployed
      name: multicluster-global-hub-postgresql
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available

```

### CODE REVIEW

**Review by clyang82 — COMMENTED** [review]
overall looks good for me.
Did you check the postgres metrics in grafana dashboard?

**Comment by yanmxa** [comment]
@clyang82 
Yes, It seems all works fine

image

**Pull request merged**
