### PR TITLE
init the db globally instead of creating the table manually in each test case

### PR DESCRIPTION
**Pull request by yanmxa**
add the following code before testing, and it will init a global hub database and create the tables, indexes and triggers
```golang
err = testpostgres.InitDatabase(testPostgres.URI)
Expect(err).NotTo(HaveOccurred())
```
resolved: https://github.com/stolostron/multicluster-global-hub/issues/466

### CODE REVIEW

**Comment by yanmxa** [comment]
I close this PR until I've done the other important things I'm doing, I'll reopen it.

**Review by clyang82 — APPROVED** [review]
Great Job!!!

**Pull request merged**
