### PR TITLE
make producer and consumer managed by controller-runtime manager.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/stolostron/multicluster-global-hub/pull/267
Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
Also make DBWorkerPool be a runnable managed by controller-runtime manager. @clyang82

**Comment by clyang82** [comment]
use controller manager to start the consumer/producer/dbworkpool does make sense for me.

/LGTM

**Pull request merged**
