### PR TITLE
Improve the performance of the status syncers for large scale

### PR DESCRIPTION
**Pull request by yanmxa**
## Scale:
- 5 managed hubs each with 300 clusters and 50 policies
- 1500 Managed Clusters
- 75000 replicas policies and 75000 replicas policy events

### Before enhancement
- ManagedClustersStatusBundle: `62998 ms`
- LocalClusterPerPolicyBundle: `2686235 ms`
- LocalCompletePolicyBundle: `249 ms`
- LocalPolicyEventBundle: `4602 ms`
```bash
2023-09-13 07:41:21 UTC INFO    statistics      {CU=5, CUQueue=0, idleDBW=10, success=50, fail=0, CU Avg=2749208 ms, DB Avg=249 ms}
[ControlInfoBundle                         (15) | conflation(successes=15, avg=901868 ms, max=2736901 ms) | storage(successes=15, avg=3 ms, max=12 ms         )] 
[LocalClustersPerPolicyBundle              (5) | conflation(successes=5, avg=823 ms, max=988 ms       ) | storage(successes=5, avg=2686235 ms, max=2713338 ms)] 
[ManagedClustersStatusBundle               (5) | conflation(successes=5, avg=2153203 ms, max=2713296 ms) | storage(successes=5, avg=62998 ms, max=86745 ms   )] 
[BaseClusterPolicyStatusEventBundle        (10) | conflation(successes=5, avg=2746458 ms, max=2779068 ms) | storage(successes=5, avg=4602 ms, max=5048 ms     )] 
[PlacementDecisionsBundle                  (5) | conflation(successes=5, avg=2215802 ms, max=2781899 ms) | storage(successes=5, avg=1 ms, max=2 ms           )] 
[LocalPolicySpecBundle                     (5) | conflation(successes=5, avg=2215804 ms, max=2781901 ms) | storage(successes=5, avg=2 ms, max=3 ms           )] 
[LocalCompleteComplianceStatusBundle       (5) | conflation(successes=5, avg=2749208 ms, max=2781904 ms) | storage(successes=5, avg=249 ms, max=354 ms       )] 
```

### After enhancement
- ManagedClustersStatusBundle: `457 ms`
- LocalClusterPerPolicyBundle: `98718 ms`
- LocalCompletePolicyBundle: `54 ms`
- LocalPolicyEventBundle: `608 ms`

~Also, we need to add the explicit primary key for the tables. Otherwise when we insert data with a default generate key in parallel goroutines. The primary key may conflict with the error like `pq: deadlock detected`~

~After adding the primary key the `pq: deadlock detected` still happens, then add the `backoff.retry` to fix it.~
**Methods to improve the performance**:
- Add the primary key for the tables
- Leverage the transaction with the primary key
- Tuning the batch size to upsert data
```bash
2023-09-15 01:09:01 UTC INFO    statistics      {CU=5, CUQueue=0, idleDBW=10, success=45, fail=0, CU Avg=27753 ms, DB Avg=5 ms}
[BaseLeafHubClusterInfoStatusBundle        (0) | conflation(successes=0, avg=0 ms, max=0 ms           ) | storage(successes=0, avg=0 ms, max=0 ms           )]
[ManagedClustersStatusBundle               (5) | conflation(successes=5, avg=22362 ms, max=109087 ms  ) | storage(successes=5, avg=457 ms, max=2047 ms      )]
[LocalPolicySpecBundle                     (5) | conflation(successes=5, avg=99861 ms, max=111136 ms  ) | storage(successes=5, avg=8 ms, max=10 ms          )]
[LocalClustersPerPolicyBundle              (5) | conflation(successes=5, avg=726 ms, max=773 ms       ) | storage(successes=5, avg=98718 ms, max=108419 ms  )]
[LocalCompleteComplianceStatusBundle       (5) | conflation(successes=5, avg=99870 ms, max=111145 ms  ) | storage(successes=5, avg=54 ms, max=70 ms         )]
[BaseClusterPolicyStatusEventBundle        (10) | conflation(successes=5, avg=97125 ms, max=108202 ms  ) | storage(successes=5, avg=608 ms, max=666 ms       )]
[ControlInfoBundle    
```

### CODE REVIEW

**Comment by clyang82** [comment]
Great improvement ! Thanks @yanmxa 

one request: Can we do batch update and batch delete?
https://gorm.io/gen/delete.html#Batch-Delete
https://gorm.io/docs/update.html#Batch-Updates

**Comment by yanmxa** [comment]
> Great improvement ! Thanks @yanmxa
> 
> one request: Can we do batch update and batch delete? https://gorm.io/gen/delete.html#Batch-Delete https://gorm.io/docs/update.html#Batch-Updates

The [Updates](https://gorm.io/docs/update.html#Batch-Updates) can't be filled with many records. Since the update isn't the bottleneck. I suggest we just combine the transaction and primary key to accelerate the operations.

For the batch deletes, one reason is like the batch update that isn't the bottleneck. The other is if we can add a condition like `delete from tablename where id in (1, 2, 3, ..)`, That will increase the complexity of SQL and my solution to improve the performance is to combine the primary key with the transaction.

**Pull request merged**
