### PR TITLE
upgrade golang to 1.22

### PR DESCRIPTION
**Pull request by ldpliu**
## Related issue(s)
https://issues.redhat.com/browse/ACM-12541
Fixes #

### CODE REVIEW

**Comment by clyang82** [comment]
You need to update `openshift/release` branch to use golang 1.22 firstly.

**Review by clyang82 — APPROVED** [review]
LGTM

**Comment by ldpliu** [comment]
The manager can not run because :
`[root@d ~]# oc logs multicluster-global-hub-manager-77d5658b85-dp4s6
/usr/local/bin/manager: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/manager)
/usr/local/bin/manager: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/manager)
/usr/local/bin/manager: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/manager)`

@yanmxa @clyang82 Any ideas?

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
