### PR TITLE
resort constants.

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/stolostron/backlog/issues/26697

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
what is the standard you are following for the constant definition? could you share it so that we can follow.

**Comment by morvencao** [comment]
@clyang82 Add a new section about constants in our development.md, see: https://github.com/stolostron/multicluster-global-hub/pull/274/files#diff-a8a79d0841d496f16553c3ab96168dae29bb5ec037a9c2b45ae3f49c5a66840b

**Pull request merged**
