### PR TITLE
remove console support

### PR DESCRIPTION
**Pull request by clyang82**
Remove console support in 2.7 since the current console is a prototype. in 2.7 release, we will have API or UI for global hub.

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
@clyang82 do we want to remove this now? then how we check the functions from console?

**Review by morvencao — COMMENTED** [review]
@clyang82 do we want to remove this now? then how we check the functions from console?

**Comment by clyang82** [comment]
we should develop the APIs to be able to use by the end user. the current UI is a prototype. it is not for production.

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
