### PR TITLE
:sparkles: add dashboard images in doc

### PR DESCRIPTION
**Pull request by ldpliu**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ldpliu** [comment]
@braddmin

**Comment by ldpliu** [comment]
> Do you need to have a document to embed those images?

Yes, After this pr merged, doc team will link to ACM/Globalhub doc.
https://github.com/stolostron/rhacm-docs/pull/6450

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
