### PR TITLE
:bug: Resync the managed hub resources upon manager startup

### PR DESCRIPTION
**Pull request by yanmxa**
## Summary

The agent produces the following log during the manager startup

```
2024-12-02T02:45:52.142Z        INFO    spec/dispatcher.go:70   event dropped due to cluster name retrieval error       {"error": "\"clustername\" not found"}
```

Related PR: https://github.com/stolostron/multicluster-global-hub/pull/1111/files#diff-7ac9c176d89d2e8f14840bfdd791862ab1781cb144a00553d02f296d3f194b34

The expected outcome is to resynchronize the resource from the agent. However, it appears that the resync signal is being blocked on the agent side!

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [x] List other manual tests you have done.

```bash
2024-12-02T03:22:24.037Z        INFO    controllers/clusterclaim_version_controller.go:31       NamespacedName: open-cluster-management/multiclusterhub
2024-12-02T03:23:58.026Z        INFO    status-resyncer syncers/resync_syncer.go:39     resync eventtypeio.open-cluster-management.operator.multiclusterglobalhubs.managedhub.info
2024-12-02T03:23:58.026Z        INFO    status-resyncer syncers/resync_syncer.go:39     resync eventtypeio.open-cluster-management.operator.multiclusterglobalhubs.managedcluster
2024-12-02T03:23:58.026Z        INFO    status-resyncer syncers/resync_syncer.go:39     resync eventtypeio.open-cluster-management.operator.multiclusterglobalhubs.policy.localspec
2024-12-02T03:23:58.026Z        INFO    status-resyncer syncers/resync_syncer.go:39     resync eventtypeio.open-cluster-management.operator.multiclusterglobalhubs.policy.localcompliance
```

### CODE REVIEW

**Comment by clyang82** [comment]
Good catch! Can you design an integration test to cover this case?

**Comment by yanmxa** [comment]
I think we can do that!

**Comment by yanmxa** [comment]
> Good catch! Can you design an integration test to cover this case?

Added the integration test to cover this case

**Pull request merged**
