### PR TITLE
Fixed the issue that agent keeps sending bundles

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Ref: https://issues.redhat.com/browse/ACM-7028

Resolved: https://github.com/stolostron/multicluster-global-hub/issues/596

### CODE REVIEW

**Review by clyang82 — APPROVED** [review]

**Comment by yanmxa** [comment]
、retest

**Comment by yanmxa** [comment]
/hold 

Need to check why the complete compliance bundle was not processed on the conflation unit.

**Comment by yanmxa** [comment]
we can find that the completeComplianceBundle is processed by the conflation unit

image

**Review by clyang82 — APPROVED** [review]

**Pull request merged**
