### PR TITLE
:sparkles: add cluster dashboard

### PR DESCRIPTION
**Pull request by ldpliu**
## Summary
cluster

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by clyang82 — COMMENTED** [review]
Can you add a banner to say this is an experimental feature?

**Comment by ldpliu** [comment]
> Can you add a banner to say this is an experimental feature?

No,
Could we add some description in https://github.com/stolostron/rhacm-docs/pull/6450
Or just in the dashboard description?

**Comment by clyang82** [comment]
both are fine for me. Please follow up. Thanks.

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
