### PR TITLE
[ACM-5468] Convert dashboards to use UTC timezone

### PR DESCRIPTION
**Pull request by dislbenn**
Jira Issue: https://issues.redhat.com/browse/ACM-5468

### CODE REVIEW

**Review by clyang82 — APPROVED** [review]
LGTM

**Comment by clyang82** [comment]
I looked at the dashboards in observability, the timezone is empty or browser. set as `utc` maybe confusion. I am thinking over whether we add start_from and end_from to help on.

**Comment by dislbenn** [comment]
@clyang82 It seems like the `utc` timezone will only be needed for dashboards that are using the `Postgres` data source. The Observability dashboards are using the timezone based on the user's local browser.

**Comment by clyang82** [comment]
> 

If you check the global hub dashboards, you can see they are using the timezone based on the user's local browser as well.

**Comment by dislbenn** [comment]
After discussion on Slack, I will close this PR to allow dashboards to remain consistent with the user's local browser timezone. We will need to document this to avoid confusion in cases where the user would expect the data to be plotted at midnight or `00:00:00`.

**Pull request closed without merging**
