### PR TITLE
delete mgh CR resource from agent

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Fixed: https://github.com/stolostron/backlog/issues/25172

### CODE REVIEW

**Comment by clyang82** [comment]
You also need to add this label for the managedclustersetbinding in the same directory.

**Comment by yanmxa** [comment]
> You also need to add this label for the managedclustersetbinding in the same directory.

Thanks, I didn't find the `managedclustersetbinding` in the agent cluster at the latest time. Since the `managedclustersetbinding` is not needed by the agent cluster, It's better to add the local label.

**Comment by clyang82** [comment]
> > You also need to add this label for the managedclustersetbinding in the same directory.
> 
> Thanks, I didn't find the `managedclustersetbinding` in the agent cluster when I removed the mgh CR. Since the `managedclustersetbinding` is not needed by the agent cluster, It's better to add the local label.

if you check this controller, it should be propagated to the regional hub cluster - https://github.com/stolostron/multicluster-global-hub/blob/main/manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go

**Comment by yanmxa** [comment]
> > > You also need to add this label for the managedclustersetbinding in the same directory.
> > 
> > 
> > Thanks, I didn't find the `managedclustersetbinding` in the agent cluster when I removed the mgh CR. Since the `managedclustersetbinding` is not needed by the agent cluster, It's better to add the local label.
> 
> if you check this controller, it should be propagated to the regional hub cluster - https://github.com/stolostron/multicluster-global-hub/blob/main/manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go

Thanks!

**Pull request merged**
