### PR TITLE
prune policy finalizer from global cluster

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Fixed: https://github.com/stolostron/backlog/issues/25316

### CODE REVIEW

**Review by clyang82 — CHANGES_REQUESTED** [review]
We still need to handle the following resources:
application
managedclusterset
managedclustersetbinding
placement

**Comment by yanmxa** [comment]
> We still need to handle the following resources: application managedclusterset managedclustersetbinding placement


> managedclusterset
Thanks! I missed the application. But for managedclusterset, managedclustersetbinding and placement, I didn't find the finalizer marked on them. I still deal with these in the latest commit.

**Pull request merged**
