### PR TITLE
fix enablemetrics csv description

### PR DESCRIPTION
**Pull request by ldpliu**
## Related issue(s)
https://issues.redhat.com/browse/ACM-11627
Fixes #

### CODE REVIEW

**Review by clyang82 — COMMENTED** [review]
I remembered the previous PR should already fix this issue. it seems it was reverted. what is the root cause?

**Comment by ldpliu** [comment]
> I remembered the previous PR should already fix this issue. it seems it was reverted. what is the root cause?

https://github.com/stolostron/multicluster-global-hub/commit/49d842ce5c70d59c1b261796eaa77da61ca825e3
This pr only update the crd files. Do not update CSV files

**Comment by clyang82** [comment]
why cannot `make bundle` detect the incomplete changes?

**Comment by ldpliu** [comment]
> why cannot `make bundle` detect the incomplete changes?

It looks bundle csv generated based on https://github.com/stolostron/multicluster-global-hub/pull/976/files#diff-46ee797ec6f0315977962a975d1ffd1463b6f0b6112faee423667a61d03bd66dL76
and it's also do not changed. I am not sure if it's possible to generate based on the crd?

**Review by clyang82 — APPROVED** [review]
LGTM

**Comment by clyang82** [comment]
`make bundle` can help on. but the current fix focused on `specDescriptors` which cannot be covered by `make bundle`.

**Pull request merged**
