### PR TITLE
upd manifests readme

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by clyang82** [comment]
we are using `git commit -s xxx` to signoff the PR so that the `dco` can be passed.

**Comment by cadawson** [comment]
Signed off by Christopher Dawson

**Comment by cadawson** [comment]
Hi @clyang82 and @yanmxa. I am using the UI to do these reviews, so I am not committing in the command line. I am not sure how to sign off on them that way. I added a comment that it is signed off. Will that work? If not, let me know what else I can do to sign off on it. Thanks.

**Comment by yanmxa** [comment]
> Hi @clyang82 and @yanmxa. I am using the UI to do these reviews, so I am not committing in the command line. I am not sure how to sign off on them that way. I added a comment that it is signed off. Will that work? If not, let me know what else I can do to sign off on it. Thanks.

Yes. There is no option to sign off with Web UI. But I found an annoying but simple way: you can manually include the `Signed-off-by` line in the commit comment box.
sample

**Pull request closed without merging**
