### PR TITLE
fix default ns in hosted mode

### PR DESCRIPTION
**Pull request by ldpliu**
## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [x] List other manual tests you have done.
Manually tested it in QE env

### CODE REVIEW

**Comment by hchenxa** [comment]
@clyang82

**Review by clyang82 — COMMENTED** [review]
I found that can be a problem to use `GHDefaultNamespace`. Can you replace all `GHDefaultNamespace` with `utils.GetDefaultNamespace()`? Thanks.

**Comment by ldpliu** [comment]
> I found that can be a problem to use `GHDefaultNamespace`. Can you replace all `GHDefaultNamespace` with `utils.GetDefaultNamespace()`? Thanks.

Yes, I have checked the code, and nothing to change.

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
