### PR TITLE
enable kafka TLS for global hub transport

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Reference: https://issues.redhat.com/browse/ACM-5205
Fixed: https://github.com/stolostron/multicluster-global-hub/issues/359

### CODE REVIEW

**Comment by clyang82** [comment]
Overall looks good. Just minor comments.

**Review by clyang82 — APPROVED** [review]
LGTM

**Review by morvencao — COMMENTED** [review]
@yanmxa do we rotate the client certificate when it is expired?

**Comment by yanmxa** [comment]
> @yanmxa do we rotate the client certificate when it is expired?

No, we haven't rotating the client certificate.

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
