### PR TITLE
update operator install mode.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/stolostron/backlog/issues/24608

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
Updated the CSV description, you can preview the CSV at https://operatorhub.io/preview @clyang82

**Comment by clyang82** [comment]
TWO comments:
1. Need to add namespace: open-cluster-management in alm-examples for mgh CR
2. I would like to merge 2 and 4 together and 3 and 5 together. for example:
> PostgreSQL needs to be installed and a database is created for multicluster global hub. A secret named storage-secret that contains the database access credential should be created in open-cluster-management namespace, eg.

kubectl create secret generic storage-secret -n open-cluster-management \
  --from-literal=database_uri=<postgresql-uri> 

Note: T[here](https://github.com/stolostron/multicluster-global-hub/tree/main/operator/config/samples/storage) is a sample script available here to install postgres in hoh-postgres namespace and create the secret storage-secret in namespace open-cluster-management automatically.

**Comment by morvencao** [comment]
Addressed comments.

**Pull request merged**
