### PR TITLE
restart grafana when datasource changed

### PR DESCRIPTION
**Pull request by ldpliu**
https://issues.redhat.com/browse/ACM-7489

### CODE REVIEW

**Comment by elgnay** [comment]
> I remember @elgnay has shown a playback that a pod can reload the credential without restarting the pod on ACM. Can we leverage that?

It's a feature of k8s client-go. I'm not sure if it is applicable for your case.

**Comment by ldpliu** [comment]
> I remember @elgnay has shown a playback that a pod can reload the credential without restarting the pod on ACM. Can we leverage that?

Thanks, we need to reload the secret in grafana, it may not applicable

**Comment by clyang82** [comment]
can we call the reload api to reload the datasource? refer to https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations

**Comment by clyang82** [comment]
refer to https://raw.githubusercontent.com/stolostron/multicluster-observability-operator/main/tools/switch-to-grafana-admin.sh how to access the grafana api.

**Comment by ldpliu** [comment]
> refer to https://raw.githubusercontent.com/stolostron/multicluster-observability-operator/main/tools/switch-to-grafana-admin.sh how to access the grafana api.

It's difficult to watch the changed secret reloaded to grafana pod. And the secret will be changed low-frequency. So I suggest restart the grafana pod.

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
