### PR TITLE
remove console related resources.

### PR DESCRIPTION
**Pull request by morvencao**
follow up PR for https://github.com/stolostron/multicluster-global-hub/pull/177

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
thanks for this PR.  can we keep using sdk version 0.23？

**Comment by morvencao** [comment]
@clyang82 no breaking change for operator-sdk from v0.19.x to the latest, so I choose a stable one.

**Review by clyang82 — COMMENTED** [review]
/lgtm

**Pull request merged**
