### PR TITLE
:sparkles:  Switch zap log for global hub operator

### PR DESCRIPTION
**Pull request by yanmxa**
## Summary

The log data
```bash
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:26       Go OS/Arch: linux/amd64
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:27       Go Version: go1.22.5
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:28       Git Commit: 944c4e82
2024-11-21T01:08:46.297Z        INFO    cmd/main.go:110 registering webhooks to the webhook server
2024-11-21T01:08:46.297Z        INFO    controller-runtime.webhook      webhook/server.go:183   Registering webhook     {"path": "/mutating"}
2024-11-21T01:08:46.297Z        INFO    cmd/main.go:115 starting manager
2024-11-21T01:08:46.297Z        INFO    controller-runtime.metrics      server/server.go:208    Starting metrics server
2024-11-21T01:08:46.297Z        INFO    manager/server.go:83    starting server {"name": "health probe", "addr": "[::]:8081"}
2024-11-21T01:08:46.297Z        INFO    controller-runtime.metrics      server/server.go:247    Serving metrics server  {"bindAddress": ":8080", "secure": false}
2024-11-21T01:08:46.297Z        INFO    controller-runtime.webhook      webhook/server.go:191   Starting webhook server
I1121 01:08:46.297970       1 leaderelection.go:254] attempting to acquire leader lease multicluster-global-hub/multicluster-global-hub-operator-lock...
2024-11-21T01:08:46.298Z        INFO    controller-runtime.certwatcher  certwatcher/certwatcher.go:161  Updated current TLS certificate
2024-11-21T01:08:46.298Z        INFO    controller-runtime.webhook      webhook/server.go:242   Serving webhook server  {"host": "", "port": 9443}
2024-11-21T01:08:46.298Z        INFO    controller-runtime.certwatcher  certwatcher/certwatcher.go:115  Starting certificate watcher
```

## Related issue(s)

Fixes # https://issues.redhat.com/browse/ACM-13421

Reference: https://github.com/stolostron/multicluster-global-hub/issues/1178

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

### CODE REVIEW

**Review by clyang82 — APPROVED** [review]
LGTM

**Comment by ldpliu** [comment]
Could we set the log level using annotation in mgh?

**Comment by yanmxa** [comment]
@ldpliu 
No, The log level is adjusted by the config map: https://github.com/stolostron/multicluster-global-hub/blob/main/doc/troubleshooting.md#change-the-mutlicluster-global-hub-log-level-at-runtime


The reason why we don't use the annotation for the CR is the operator log level can't be modified by it

**Pull request merged**
