### PR TITLE
:memo: Refactor the structure of the global hub agent

### PR DESCRIPTION
**Pull request by yanmxa**
## Related issue(s)

Fixes # https://issues.redhat.com/browse/ACM-14760

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [x] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

### CODE REVIEW

**Comment by yanmxa** [comment]
Prow issue, retest it
```bash
INFO[2024-10-12T10:10:10Z] Ran for 0s                                   
ERRO[2024-10-[12](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stolostron_multicluster-global-hub/1156/pull-ci-stolostron-multicluster-global-hub-main-test-integration/1845044250014650368#1:build-log.txt%3A12)T10:10:10Z] Some steps failed:                           
ERRO[2024-10-12T10:10:10Z] 
  * could not initialize namespace: could not update namespace to add labels, TTLs and active annotations: Operation cannot be fulfilled on namespaces "ci-op-t6xf1z2c": the object has been modified; please apply your changes to the latest version and try again 
INFO[2024-10-12T10:10:10Z] Reporting job state 'failed' with reason 'initializing_namespace'
```

/test test-integration

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
