### PR TITLE
Have a migration controller to reconcile the managedclustermigation CR

### PR DESCRIPTION
**Pull request by clyang82**
## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [x] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
how do we delete migration CR? will it be left in the cluster after the managed cluster migration?

**Comment by clyang82** [comment]
> how do we delete migration CR? will it be left in the cluster after the managed cluster migration?

They are 2 options:
1. remove the migration CR once the migration is done
2. keep it in the cluster so that we can check the status.
Need to think over. for dev preview, just leave it in the cluster.

**Pull request merged**
