### PR TITLE
switch the grafana clusterrole to role

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>
Referrences: https://issues.redhat.com/browse/ACM-4795

### CODE REVIEW

**Comment by yanmxa** [comment]
> grafana

Yes, I have replaced the `clusterrole` with `role` and verified that we can retrieve resources by the grafana from the database.

**Comment by clyang82** [comment]
That's good.

/lgtm

**Review by clyang82 — APPROVED** [review]

**Pull request merged**
