### PR TITLE
Do not skip the provider button

### PR DESCRIPTION
**Pull request by clyang82**
ref to https://github.com/stolostron/backlog/issues/16412 to fix https://issues.redhat.com/browse/ACM-4598

### CODE REVIEW

**Comment by yanmxa** [comment]
@clyang82 Does this mean that when the token expires, and I click this button to login again it will clear the client's cookies?

**Comment by morvencao** [comment]
@yanmxa manually clicking provider button should refresh the cookies.

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
