### PR TITLE
fix incarnation in hosted mode.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://issues.redhat.com/browse/ACM-2023
Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
We also need to parse the flag parameter before using the `ctrl.GetConfigOrDie()`. 
https://github.com/stolostron/multicluster-global-hub/blob/a3bb618aaf32f7bfe1cf9504ad0996fca49c33a5/agent/cmd/agent/main.go#L39

Otherwise, It might not get the [kubeconfig](https://github.com/stolostron/multicluster-global-hub/blob/a3bb618aaf32f7bfe1cf9504ad0996fca49c33a5/operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml#L24) flag when executing the `ctrl.GetConfigOrDie()`

**Comment by morvencao** [comment]
will fix that in another PR

**Pull request merged**
