### PR TITLE
Enable placement syncers for global resouces

### PR DESCRIPTION
**Pull request by yanmxa**
## Summary

We will only enable the placement/placementrule/placementdecision for global resources and disable them for local resource

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by yanmxa** [comment]
> why need this change? is it introduced by code refactor?

I just find that the placement, placementrule and placementdecision in the message queue. But we don't need it for now.

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
