### PR TITLE
Limit uncontrolled growth of the postgre `pg_wal` dir

### PR DESCRIPTION
**Pull request by yanmxa**
If there is some issue happening with the transaction. The logs in this file will continue to accumulate until all disk space is consumed. Like:
```
sh-4.4$ pwd
/pgdata
sh-4.4$ du -sh ./*
16K	./lost+found
7.1G	./pg14
30G	./pg14_wal
8.0K	./pgbackrest
```
ref: https://github.com/CrunchyData/postgres-operator/issues/2115, https://github.com/CrunchyData/postgres-operator/issues/2813,  https://thebuild.com/blog/2023/03/23/the-importance-of-max_wal_size/

### CODE REVIEW

**Comment by yanmxa** [comment]
ref: https://github.com/stolostron/multicluster-global-hub/pull/601

**Comment by clyang82** [comment]
Need to modify here too - https://github.com/stolostron/multicluster-global-hub/blob/fb3ae7d51b41233d0efa2be69af1d18bbc22faed/operator/pkg/postgres/postgres.go#L166

**Comment by yanmxa** [comment]
> Need to modify here too -
> 
> https://github.com/stolostron/multicluster-global-hub/blob/fb3ae7d51b41233d0efa2be69af1d18bbc22faed/operator/pkg/postgres/postgres.go#L166

Done.

**Pull request merged**
