### PR TITLE
add retention record with deleted time

### PR DESCRIPTION
**Pull request by hchenxa**
- rename the partition to retention
- add deleted record UT

### CODE REVIEW

**Comment by hchenxa** [comment]
and passed the local test below:

**Comment by hchenxa** [comment]
and passed the local test below:
```
Success. You can now start the database server using:

    /Users/hchenxa/.embedded-postgres-go-1821/extracted/bin/pg_ctl -D /Users/hchenxa/.embedded-postgres-go-1821/extracted/data -l logfile start

waiting for server to start....2023-08-25 16:19:35.452 CST [39577] LOG:  starting PostgreSQL 12.11 on x86_64-apple-darwin, compiled by Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn), 64-bit
2023-08-25 16:19:35.455 CST [39577] LOG:  listening on IPv6 address "::1", port 1821
2023-08-25 16:19:35.455 CST [39577] LOG:  listening on IPv4 address "127.0.0.1", port 1821
2023-08-25 16:19:35.456 CST [39577] LOG:  listening on Unix socket "/tmp/.s.PGSQL.1821"
2023-08-25 16:19:35.468 CST [39578] LOG:  database system was shut down at 2023-08-25 16:19:35 CST
2023-08-25 16:19:35.471 CST [39577] LOG:  database system is ready to accept connections
 done
server started
script 1.schemas.sql executed successfully.
script 2.tables.sql executed successfully.
script 3.functions.sql executed successfully.
script 4.trigger.sql executed successfully.
SSthe expired partition table is created:  event.local_policies_2022_02
the expired partition table is created:  event.local_root_policies_2022_02
the expired partition table is created:  history.local_compliance_2022_02
the deleted record is created:  status.managed_clusters
the deleted record is created:  status.leaf_hubs
the deleted record is created:  local_spec.policies
deleting the expired partition table:  event.local_policies_2022_02
deleting the expired partition table:  event.local_root_policies_2022_02
deleting the expired partition table:  history.local_compliance_2022_02
deleting the expired record in table:  status.managed_clusters
deleting the expired record in table:  status.leaf_hubs
deleting the expired record in table:  local_spec.policies
•table_name(event.local_policies) | min(local_policies_2022_03) | max(local_policies_2023_09) | min_deletion(0001-01-01)
table_name(event.local_root_policies) | min(local_root_policies_2022_03) | max(local_root_policies_2023_09) | min_deletion(0001-01-01)
table_name(history.local_compliance) | min(local_compliance_2022_03) | max(local_compliance_2023_09) | min_deletion(0001-01-01)
table_name(status.managed_clusters) | min() | max() | min_deletion(0001-01-01)
table_name(status.leaf_hubs) | min() | max() | min_deletion(0001-01-01)
table_name(local_spec.policies) | min() | max() | min_deletion(0001-01-01)
•waiting for server to shut down...2023-08-25 16:19:37.891 CST [39577] LOG:  received fast shutdown request
.2023-08-25 16:19:37.891 CST [39577] LOG:  aborting any active transactions
2023-08-25 16:19:37.891 CST [39586] FATAL:  terminating connection due to administrator command
2023-08-25 16:19:37.893 CST [39577] LOG:  background worker "logical replication launcher" (PID 39584) exited with exit code 1
2023-08-25 16:19:37.893 CST [39579] LOG:  shutting down
2023-08-25 16:19:37.921 CST [39577] LOG:  database system is shut down
 done
server stopped


Ran 2 of 4 Specs in 12.190 seconds
```

**Comment by yanmxa** [comment]
@clyang82 I remember you suggest renaming the `data-retention` to `data-partition`. Do you have any comments?

Personally, I would like to use the former. It seems this name can provide the customer with a clearer concept of what this job is for. And the `data-partition` seems more appropriate for the engineer's expression to show how the job works.

**Review by clyang82 — APPROVED** [review]

**Pull request merged**
