### PR TITLE
add known issue

### PR DESCRIPTION
**Pull request by ldpliu**
https://issues.redhat.com/browse/ACM-6230
https://issues.redhat.com/browse/ACM-7461

### CODE REVIEW

**Comment by clyang82** [comment]
maybe we also need to log a task for ID to add them into official document. what do you think?

**Comment by ldpliu** [comment]
> maybe we also need to log a task for ID to add them into official document. what do you think?

Yes, created.
https://issues.redhat.com/browse/ACM-8264

**Comment by clyang82** [comment]
Thanks

/lgtm
/approved

**Pull request merged**
