### PR TITLE
fixed the nil pointer bug when the operand field is missing

### PR DESCRIPTION
**Pull request by yanmxa**
ref: https://issues.redhat.com/browse/ACM-6780

### CODE REVIEW

**Comment by clyang82** [comment]
@yanmxa Do we have the default value for the retention? in other words, is this default value set - https://github.com/stolostron/multicluster-global-hub/blob/f8719071dbc6e050a225a754657d2f9ed72bda9c/operator/apis/v1alpha3/multiclusterglobalhub_types.go#L112C1-L112C32

**Comment by yanmxa** [comment]
> 

Yes, we have the default value for `retention`. But haven't the default value for postgreConfig pointer: https://github.com/stolostron/multicluster-global-hub/blob/f8719071dbc6e050a225a754657d2f9ed72bda9c/operator/apis/v1alpha3/multiclusterglobalhub_types.go#L103

**Comment by yanmxa** [comment]
I close the PR, since after simplifying the Global Hub Operand in this [PR](https://github.com/stolostron/multicluster-global-hub/pull/576). The error will disappear~

**Pull request closed without merging**
